### ISSUE TITLE
Nodes in Polisy but not in ISY

### ISSUE THREAD

**Issue by macjeff** [dbarentine/udi-totalconnect-poly#6] opened 2020-02-13 23:51 UTC
I have logs from Polisy and your nodeserver

I installed totalconnect into polisy- success
installed nodeserver to ISY success.
Rebooted Admin console
TotalConnect Controller showed up with TRUE status.
NodeServer showed 1 node.
Put in my config details with 41 zones.
Restarted node server
All 41 zones showed up in logs and the node count in Polisy went to 41.
No nodes show up in ISY.
I rebooted ISY, admin console, and polisy
I see errors like this as its trying to update nodes in ISY - 

020-2-13 18:23:40 [polyglot] info: TotalConnect(16): Processing command: status
2020-2-13 18:23:40 [polyglot] info: TotalConnect(16): Processing command: status
2020-2-13 18:23:40 [polyglot] info: TotalConnect(16): Processing command: status
2020-2-13 18:23:40 [polyglot] error: TotalConnect(16): n016_z_5651_2 or GV0 does not exist - ISY returned 404
2020-2-13 18:23:40 [polyglot] info: TotalConnect(16): Processing command: status
2020-2-13 18:23:40 [polyglot] error: TotalConnect(16): n016_z_5651_2 or GV0 does not exist - ISY returned 404
2020-2-13 18:23:40 [polyglot] error: TotalConnect(16): n016_z_5651_2 or GV1 does not exist - ISY returned 404
2020-2-13 18:23:40 [polyglot] error: TotalConnect(16): n016_z_5651_2 or GV1 does not exist - ISY returned 404

All my other 15 nodeservers work.  I even uninstalled and one reinstalled and all those nodes came right in.   So its just something with this one.

I will try the PGC version later.

**Comment by macjeff** [comment] 2020-02-14 03:08
Found the bug!!!  This will help you...

First it totally crashes PGC.  Polisy just never installs nodes.  PGC keeps bombarding the ISY with commands and actually crashes the Portal and ISY goes on and offline from the portal but fixing the bug will solve that issue too. 
The alarm company had a   /   in our alarm panel name.
Removed the / and Polisy started working.   
If you cant support it thats fine but add a check that if someone has a / in their alarm system to send message and STOP loading zones.   In PGC the crash happens when the zones start loading.

Hope this helps but for now I removed the / and working fine

**Comment by dbarentine** [comment] 2020-02-14 06:23
When you say you removed the / I'm assuming you removed it from within Total Connect itself right? And then were able to successfully able to complete discovery in the nodeserver.

I'll have to take a look and see what the naming limitations are within the ISY. Obviously it doesn't like slashes but I suspect there are other characters that would trigger this as well.

On discovery it's probably safest to just remove anything that isn't a-z, a space, or 0-9 which should resolve the issue. This should be pretty straightforward to resolve.

**Comment by macjeff** [comment] 2020-02-14 15:24
I deleted the Nodeserever and re-added it.  Also another issue is every so often it goes offline.  If I restart nodeserver it does not help but if I restart POLYGLOT it comes right back.  However looking at the logs it went down about 1 am while I was sleeping and came back at 2am.  You can see the logs saying cant connect to panel.    This is from this AM.  It gets that when updating any zone or if I arm or disarm.   But again a restart of polyglot brought it right back

2020-02-14 09:30:18,139 [Controller] [DEBUG] Query zone z_5651_40
2020-02-14 09:30:18,307 [Controller] [WARNING] Unable to refresh zone, code 4101 message We are unable to connect to the security panel. Please try again later or contact support
2020-02-14 09:30:18,308 [Controller] [DEBUG] Query zone z_5651_1
2020-02-14 09:30:18,567 [Controller] [WARNING] Unable to refresh zone, code 4101 message We are unable to connect to the security panel. Please try again later or contact support
2020-02-14 09:30:18,733 [Controller] [ERROR] Disarming panel panel_5651 failed Could not disarm system. ResultCode: 4101. ResultData: We are unable to connect to the security panel. Please try again later or contact support

**Comment by dbarentine** [comment] 2020-02-14 18:37
Yeah I've been seeing that one as well and haven't been able to figure out why yet. I suspect it's got something to do with the authentication session. But haven't figured out why a restart of the nodeserver doesn't fix it.

**Comment by dbarentine** [comment] 2020-02-19 07:06
@macjeff version 1.3.0 should now scrub the names of any characters that the ISY would find problematic. So hopefully that should address the first issue.

For the second one what I've done is set up the code to refresh the authentication session every so often. Right now the default is 120 minutes. It is adjustable via the settings inside Polyglot. As I said above I suspect that the issue is the session expires and that is why we can't connect to the panel. By refreshing it we should resolve that.

I'm going to close this issue for now. But if the problem re-occurs after the update let me know and we can get a new issue started to track it.

**Closed as completed by dbarentine** 2020-02-19 07:06 UTC
Labels: bug
